name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          brew install ninja
          
          cmake -G Ninja -B build
          cmake --build build -v
        env:
          CC: gcc-9
          CXX: g++-9

      - name: Run test
        run: |
          export PATH="$PWD/build:$PATH"
          
          bash -x ./tests/test.sh
  
  windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          iwr -useb get.scoop.sh | iex
          scoop install ninja
          scoop install gcc

          $env:CC = "${HOME}\scoop\apps\gcc\current\bin\gcc.exe"
          $env:CXX = "${HOME}\scoop\apps\gcc\current\bin\g++.exe"

          cmake -G Ninja -B build
          cmake --build build -v
        shell: powershell
        
      - name: Run test
        run: .\tests\test.ps1
        shell: powershell